apiVersion: v1
kind: ConfigMap
metadata:
  name: idv-statsd-config
data:
  mappings.yml: |
    mappings:
      - match: "idv.(.*)_http_method_(.*)_route_(.*)_status_(.*)_duration"
        name: "idv_${1}_http_duration"
        match_type: regex
        labels:
          service: "$1"
          method: "$2"
          url_rule: "$3"
          status: "$4"

      - match: "idv.(.*)_http_status_(.*)_total"
        name: "idv_${1}_http_request_total"
        match_type: regex
        labels:
          service: "$1"
          status: "$2"

      - match: "idv.(.*)_(.*)_duration"
        name: "idv_${1}_duration"
        match_type: regex
        labels:
          service: "$1"
          operation: "$2"

      - match: "idv.(.*)_(.*)_(.*)_condition_eval_count"
        name: "idv_workflow_step_condition_eval_count"
        match_type: regex
        labels:
          workflow_id: "$1"
          condition: "$2"
          result: "$3"

      - match: "idv.(.*)_(.*)_error_count"
        name: "idv_error"
        match_type: regex
        labels:
          service: "$1"
          operation: "$2"

      - match: "idv.(.*)_(.*)_success_count"
        name: "idv_${1}_success_count"
        match_type: regex
        labels:
          service: "$1"
          operation: "$2"

      - match: "idv.(.*)_(.*)_error_count"
        name: "idv_${1}_error_count"
        match_type: regex
        labels:
          service: "$1"
          operation: "$2"

      - match: "idv.(.*)_(.*)_count"
        name: "idv_${1}_total"
        match_type: regex
        labels:
          service: "$1"
          operation: "$2"
