apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "idv.fullname" . }}-config
  labels: {{- include "idv.labels" . | nindent 4 }}
data:
  idv-config: |+
    {{- include "idv.config" . | nindent 4 }}
