apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}-celery
  labels:
    {{- include "celery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:
      {{- include "celery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/celery/celery-configmap.yaml") . | sha256sum }}
        {{- if .Values.gateway.podAnnotations }}
        {{- toYaml .Values.gateway.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "celery.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.celery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.celery.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "gateway.fullname" . }}-celery
          securityContext:
            {{- toYaml .Values.celery.securityContext | nindent 12 }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          command: ["celery"]
          args:
            - "--app=gateway"
            - "worker"
            - "--loglevel=INFO"
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "celery.config.name" . }}
          env:
            {{- include "celery_envs" . | indent 10 }}
          volumeMounts:
            {{- if .Values.celery.extraVolumeMounts }}
              {{- toYaml .Values.celery.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.celery.extraVolumes }}
          {{- toYaml  .Values.celery.extraVolumes | nindent 8 }}
        {{- end }}
