apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}-celery
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.gateway.podAnnotations }}
        {{- toYaml .Values.gateway.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.celery.podAnnotations }}
          {{- toYaml .Values.celery.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.celery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.celery.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.celery.securityContext | nindent 12 }}
          image: "{{ .Values.celery.image.repository }}:{{ .Values.celery.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.celery.image.pullPolicy }}
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
          env:
            {{- include "gateway.redis" . | nindent 12 }}
            {{- include "celery_envs" . | nindent 12 }}
          volumeMounts:
            {{- if .Values.celery.extraVolumeMounts }}
              {{- toYaml .Values.celery.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.celery.extraVolumes }}
          {{- toYaml  .Values.celery.extraVolumes | nindent 8 }}
        {{- end }}