apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idv.fullname" . }}-statsd
  labels:
    {{- include "idv.labels" . | nindent 4 }}
    component: statsd
spec:
  {{- if not .Values.statsd.autoscaling.enabled }}
  replicas: {{ .Values.statsd.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "idv.selectorLabels" . | nindent 6 }}
      component: statsd
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configs/idv-statsd.yaml") . | sha256sum }}
        checksum/version: {{ .Values.versionSha | quote }}
        forceUpdate: {{ .Values.deployment.forceUpdate | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "idv.labels" . | nindent 8 }}
        component: statsd
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      volumes:
      - name: config
        configMap:
          name: idv-statsd-config
          defaultMode: 420
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: statsd
        image: {{ .Values.statsd.image.repository }}:{{ .Values.statsd.image.tag }}
        imagePullPolicy: {{ .Values.statsd.image.pullPolicy }}
        args:
        {{- range .Values.statsd.args }}
          - '{{ . }}'
        {{- end }}
        resources: {{- toYaml .Values.statsd.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        {{- if .Values.statsd.probes.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: {{ .Values.statsd.probes.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.statsd.probes.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.statsd.probes.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.statsd.probes.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.statsd.probes.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.statsd.probes.livenessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.statsd.probes.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /metrics
            port: {{ .Values.statsd.probes.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.statsd.probes.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.statsd.probes.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.statsd.probes.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.statsd.probes.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.statsd.probes.readinessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.statsd.probes.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.statsd.probes.startupProbe.port }}
          initialDelaySeconds: {{ .Values.statsd.probes.startupProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.statsd.probes.startupProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.statsd.probes.startupProbe.periodSeconds }}
          failureThreshold: {{ .Values.statsd.probes.startupProbe.failureThreshold }}
          successThreshold: {{ .Values.statsd.probes.startupProbe.successThreshold }}
        {{- end }}
        {{- with .Values.statsd.ports }}
        ports: {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        env: {{- tpl (toYaml .Values.env) . | nindent 10 }}
        {{- with .Values.statsd.nodeSelector }}
        nodeSelector: {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.statsd.affinity }}
        affinity: {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.statsd.tolerations }}
        tolerations: {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
          - name: config
            mountPath: /etc/statsd-exporter/mappings.yml
            subPath: mappings.yml
