{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "idv.serviceAccountName" . }}
  annotations:
    {{- tpl (toYaml .Values.serviceAccount.annotations) . | nindent 4 }}
{{- end }}
