apiVersion: v1
kind: Service
metadata:
  name: {{ include "idv.fullname" . }}-api
  labels:
    {{- include "idv.labels" . | nindent 4 }}
    component: api
    mode: {{ .Values.config.mode }}
  {{- with .Values.api.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  {{- if .Values.api.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.api.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.api.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.api.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "idv.selectorLabels" . | nindent 4 }}
    component: api
    mode: {{ .Values.config.mode }}
