{{ if eq .Values.config.mode "cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "idv.fullname" . }}-api
  labels:
    {{- include "idv.labels" . | nindent 4 }}
    component: api
spec:
  ports:
  {{- range .Values.api.service.ports }}
  - port: {{ tpl (.port | toString) $ }}
    targetPort: {{ tpl (.targetPort | toString) $ }}
    protocol: {{ tpl .protocol $ }}
    name: {{ tpl .name $ }}
  {{- end }}
  selector: 
    {{- include "idv.selectorLabels" . | nindent 4 }}
    component: api
  type: {{ .Values.api.service.type }}
{{ end }}
