apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}-flower
  labels:
    {{- include "flower.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flower.replicas }}
  selector:
    matchLabels:
      {{- include "flower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/flower/flower-configmap.yaml") . | sha256sum }}
        {{- if .Values.gateway.podAnnotations }}
        {{- toYaml .Values.gateway.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "flower.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.flower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.flower.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "gateway.fullname" . }}-flower
          securityContext:
            {{- toYaml .Values.flower.securityContext | nindent 12 }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          command: ["celery"]
          args:
            - "--app=config"
            - "flower"
          ports:
            - name: flower
              containerPort: 5555
              protocol: TCP
          resources:
            {{- toYaml .Values.flower.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "flower.config.name" . }}
          env:
            {{- include "flower_envs" . | indent 10 }}
          volumeMounts:
            {{- if .Values.flower.extraVolumeMounts }}
              {{- toYaml .Values.flower.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.flower.extraVolumes }}
          {{- toYaml  .Values.flower.extraVolumes | nindent 8 }}
        {{- end }}
