apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-flower
  labels:
    {{- include "flower.labels" . | nindent 4 }}
  {{- with .Values.flower.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: flower
      protocol: TCP
      name: flower
  {{- if eq .Values.flower.service.type "LoadBalancer" }}
  {{- if .Values.flower.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.flower.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.flower.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.flower.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "flower.selectorLabels" . | nindent 4 }}
