{{ if eq .Values.config.mode "cluster" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    component: scheduler
    app: idv
spec:
  {{- if not .Values.scheduler.autoscaling.enabled }}
  replicas: {{ .Values.scheduler.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
      component: scheduler
      product: idv
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configs/idv-config.yaml") . | sha256sum }}
        checksum/version: {{ .Values.versionSha | quote }}
        forceUpdate: {{ .Values.deployment.forceUpdate | quote }}
      labels:
        app.kubernetes.io/name: scheduler
        component: scheduler
        product: idv
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.licenseSecretName }}
      - name: license
        secret:
          secretName: {{ .Values.licenseSecretName }}
      {{- end }}
      - name: idv-config
        configMap:
          name: idv-config
          items:
            - key: idv-config
              path: idv-config.yaml
      containers:
      - name: scheduler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.scheduler.resources | nindent 12 }}
        volumeMounts:
        {{- if .Values.licenseSecretName }}
        - name: license
          mountPath: /app/extBin/unix/regula.license
          subPath: regula.license
          readOnly: true
        {{- end }}
        - name: idv-config
          mountPath: /etc/idv/idv-config.yaml
          subPath: idv-config.yaml
        command: ["idv"]
        args: ["scheduler", "start"]
        env:
          {{- tpl (toYaml .Values.env) . | nindent 12 }}
        {{- with .Values.scheduler.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.scheduler.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.scheduler.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: 30
{{ end }}