apiVersion: v1
kind: Service
metadata:
  name: {{ include "idv.fullname" . }}-statsd
  labels:
    {{- include "idv.labels" . | nindent 4 }}
    component: statsd
spec:
  ports:
  {{- range .Values.statsd.service.ports }}
  - port: {{ tpl (.port | toString) $ }}
    targetPort: {{ tpl (.targetPort | toString) $ }}
    protocol: {{ tpl .protocol $ }}
    name: {{ tpl .name $ }}
  {{- end }}
  selector:
    {{- include "idv.selectorLabels" . | nindent 4 }}
    component: statsd
  type: {{ .Values.statsd.service.type }}
  