apiVersion: v1
kind: Service
metadata:
  name: {{ include "idv.portal.fullname" . }}
  labels:
    {{- include "idv.labels" . | nindent 4 }}
    component: "portal"
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: portal
      protocol: TCP
      name: portal
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "idv.selectorLabels" . | nindent 4 }}
    component: "portal"
