apiVersion: v1
kind: ConfigMap
metadata:
  name: idv-statsd-config
data:
  mappings.yml: |
    mappings:
      {{- range .Values.statsd.mappings }}
      - match: "{{ .match }}"
        name: "{{ .name }}"
        match_type: {{ .match_type }}
        labels:
          {{- range $key, $value := .labels }}
          {{ $key }}: "{{ $value }}"
          {{- end }}
      {{- end }}
