{{- if .Values.gateway.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gateway.fullname" . }}
  {{- if .Values.gateway.serviceMonitor.namespace }}
  namespace: {{ .Values.gateway.serviceMonitor.namespace }}
  {{- end }}
  labels: {{- include "gateway.labels" . | nindent  4 }}
    {{- if .Values.gateway.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.gateway.serviceMonitor.additionalLabels | nindent  4 }}
    {{- end }}
spec:
  endpoints:
    - honorLabels: true
      interval: {{ .Values.gateway.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.gateway.serviceMonitor.scrapeTimeout }}
      path: /metrics
      port: gateway
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
{{- end }}
