apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: gateway
      protocol: TCP
      name: gateway
  {{- if eq .Values.gateway.service.type "LoadBalancer" }}
  {{- if .Values.gateway.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.gateway.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.gateway.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
