apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.config.name" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  {{- include "gateway.config" . | nindent 2 }}
