apiVersion: v2
name: idv
home: https://idv.regula.app/
version: 0.1.3
appVersion: "2.3.5"
description: IDV Platform. On-premise and cloud integration
icon: https://secure.gravatar.com/avatar/71a5efd69d82e444129ad18f51224bbb.jpg
keywords:
  - regula
  - idv
  - idv-platform
  - regulaforensics
dependencies:
  - name: opensearch
    version: 2.19.0
    repository: https://opensearch-project.github.io/helm-charts
    condition: opensearch.enabled
  - name: valkey
    version: 3.0.8
    repository: https://charts.bitnami.com/bitnami
    condition: valkey.enabled
  - name: mongodb
    version: 16.5.17
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
type: application
