apiVersion: v2
name: idv
description: IDV Platform. On-premise and cloud integration

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.3.5"

dependencies:
  - name: opensearch
    version: 2.19.0
    repository: https://opensearch-project.github.io/helm-charts
    condition: opensearch.enabled
  - name: valkey
    version: 3.0.8
    repository: https://charts.bitnami.com/bitnami
    condition: valkey.enabled
  - name: mongodb
    version: 16.5.17
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
