apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "idv.proxy.fullname" . }}
  labels:
    {{- include "idv.labels" . | nindent 4 }}
    component: "proxy"
data:
  envoy.yaml: |
    {{- if .Values.proxy.configYaml }}
      {{- tpl .Values.proxy.configYaml . | nindent 4 }}
    {{- else }}
    overload_manager:
      refresh_interval: 0.25s
      resource_monitors:
      - name: "envoy.resource_monitors.fixed_heap"
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
          # TODO: Tune for your system.
          max_heap_size_bytes: 2147483648  # 2 GiB
      actions:
      - name: "envoy.overload_actions.shrink_heap"
        triggers:
        - name: "envoy.resource_monitors.fixed_heap"
          threshold:
            value: 0.95
      - name: "envoy.overload_actions.stop_accepting_requests"
        triggers:
        - name: "envoy.resource_monitors.fixed_heap"
          threshold:
            value: 0.98

    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9090

    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        per_connection_buffer_limit_bytes: 32768  # 32 KiB
        filter_chains:
          filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
                - name: envoy.access_loggers.file
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /dev/stdout
              use_remote_address: true
              normalize_path: true
              merge_slashes: true
              path_with_escaped_slashes_action: UNESCAPE_AND_REDIRECT
              common_http_protocol_options:
                idle_timeout: 3600s  # 1 hour
                # headers_with_underscores_action: REJECT_REQUEST
              http2_protocol_options:
                max_concurrent_streams: 100
                initial_stream_window_size: 65536  # 64 KiB
                initial_connection_window_size: 1048576  # 1 MiB
              # stream_idle_timeout: 300s  # 5 mins, must be disabled for long-lived and streaming requests
              # request_timeout: 300s  # 5 mins, must be disabled for long-lived and streaming requests
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                virtual_hosts:
                - name: coordinator
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/api" }
                    route: { cluster: coordinator, idle_timeout: 15s }  # idle_timeout must be disabled for long-lived and streaming requests
      clusters:
      - name: coordinator
        type: STRICT_DNS
        per_connection_buffer_limit_bytes: 32768  # 32 KiB
        load_assignment:
          cluster_name: idv_coordinator
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ include "idv.coordinator.fullname" . }}
                    port_value: {{ .Values.coordinator.service.port }}
    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          envoy:
            resource_limits:
              listener:
                example_listener_name:
                  connection_limit: 10000
          overload:
            global_downstream_max_connections: 50000
    {{- end }}