apiVersion: v1
kind: Service
metadata:
  name: {{ include "idv.proxy.fullname" . }}
  labels:
    {{- include "idv.labels" . | nindent 4 }}
    component: "proxy"
  {{- with .Values.proxy.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  {{- if .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.proxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.proxy.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "idv.selectorLabels" . | nindent 4 }}
    component: "proxy"
