name: Release Private Charts

on:
  push:
    branches:
      - private
    paths:
      - "charts/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Add Dependency Chart Repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Package Helm Charts
        run: |
          mkdir -p helm-releases
          helm package charts/* -d helm-releases/

      - name: Update Helm Repo Index
        run: |
          helm repo index helm-releases --merge helm-releases/index.yaml --url https://raw.githubusercontent.com/regulaforensics/helm-test/private/helm-releases

      - name: Commit and Push Changes
        run: |
          git add helm-releases/*
          git commit -m "Updated Helm charts from ref: $GITHUB_SHA"
          git push
